//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisioAPI.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int IdCitas { get; set; }
        public int IdUsuarioFk { get; set; }
        public int IdDoctorFK { get; set; }
        public string condicion { get; set; }
        public System.DateTime Hora { get; set; }
        public bool status { get; set; }
    
        public virtual Doctores Doctores { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
