//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisioAPI.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public int idComentarios { get; set; }
        public int idUsuariosFk { get; set; }
        public string textoComentario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
