//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisioAPI.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public int idHorario { get; set; }
        public int IdDiaFK { get; set; }
        public int IdDoctorFK { get; set; }
        public System.DateTime HoraEntrada { get; set; }
        public System.DateTime HoraSalida { get; set; }
    
        public virtual Dias Dias { get; set; }
        public virtual Doctores Doctores { get; set; }
    }
}
