//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisioAPI.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MOSSAEntities : DbContext
    {
        public MOSSAEntities()
            : base("name=MOSSAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABITACORA> ABITACORA { get; set; }
        public virtual DbSet<Citas> Citas { get; set; }
        public virtual DbSet<Comentarios> Comentarios { get; set; }
        public virtual DbSet<Dias> Dias { get; set; }
        public virtual DbSet<Doctores> Doctores { get; set; }
        public virtual DbSet<EBITACORA> EBITACORA { get; set; }
        public virtual DbSet<Expediente> Expediente { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
        public virtual DbSet<Planilla> Planilla { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<Consultar_Citas_Doctor_Result> Consultar_Citas_Doctor(Nullable<int> idDoctor)
        {
            var idDoctorParameter = idDoctor.HasValue ?
                new ObjectParameter("IdDoctor", idDoctor) :
                new ObjectParameter("IdDoctor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consultar_Citas_Doctor_Result>("Consultar_Citas_Doctor", idDoctorParameter);
        }
    
        public virtual ObjectResult<Consultar_Citas_Paciente_Result> Consultar_Citas_Paciente(Nullable<int> idPaciente)
        {
            var idPacienteParameter = idPaciente.HasValue ?
                new ObjectParameter("IdPaciente", idPaciente) :
                new ObjectParameter("IdPaciente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consultar_Citas_Paciente_Result>("Consultar_Citas_Paciente", idPacienteParameter);
        }
    
        public virtual ObjectResult<Consultar_Datos_Usuario_Result> Consultar_Datos_Usuario(string email, string contrasenna)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consultar_Datos_Usuario_Result>("Consultar_Datos_Usuario", emailParameter, contrasennaParameter);
        }
    
        public virtual ObjectResult<Consultar_Doctor_Estado_Result> Consultar_Doctor_Estado(Nullable<int> indicador)
        {
            var indicadorParameter = indicador.HasValue ?
                new ObjectParameter("indicador", indicador) :
                new ObjectParameter("indicador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consultar_Doctor_Estado_Result>("Consultar_Doctor_Estado", indicadorParameter);
        }
    
        public virtual ObjectResult<Consultar_Expediente_Paciente_Result> Consultar_Expediente_Paciente(Nullable<int> idPaciente)
        {
            var idPacienteParameter = idPaciente.HasValue ?
                new ObjectParameter("IdPaciente", idPaciente) :
                new ObjectParameter("IdPaciente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consultar_Expediente_Paciente_Result>("Consultar_Expediente_Paciente", idPacienteParameter);
        }
    
        public virtual ObjectResult<Consultar_IdDoctor_Result> Consultar_IdDoctor(Nullable<int> idDoctor)
        {
            var idDoctorParameter = idDoctor.HasValue ?
                new ObjectParameter("idDoctor", idDoctor) :
                new ObjectParameter("idDoctor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consultar_IdDoctor_Result>("Consultar_IdDoctor", idDoctorParameter);
        }
    
        public virtual ObjectResult<Consultar_IdPlanilla_Result> Consultar_IdPlanilla(Nullable<int> idPlanilla)
        {
            var idPlanillaParameter = idPlanilla.HasValue ?
                new ObjectParameter("IdPlanilla", idPlanilla) :
                new ObjectParameter("IdPlanilla", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consultar_IdPlanilla_Result>("Consultar_IdPlanilla", idPlanillaParameter);
        }
    
        public virtual ObjectResult<Consultar_Planilla_Doctor_Result> Consultar_Planilla_Doctor(Nullable<int> idDoctor)
        {
            var idDoctorParameter = idDoctor.HasValue ?
                new ObjectParameter("IdDoctor", idDoctor) :
                new ObjectParameter("IdDoctor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consultar_Planilla_Doctor_Result>("Consultar_Planilla_Doctor", idDoctorParameter);
        }
    
        public virtual ObjectResult<Consultar_Usuarios_Estado_Result> Consultar_Usuarios_Estado(Nullable<int> indicador)
        {
            var indicadorParameter = indicador.HasValue ?
                new ObjectParameter("indicador", indicador) :
                new ObjectParameter("indicador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consultar_Usuarios_Estado_Result>("Consultar_Usuarios_Estado", indicadorParameter);
        }
    
        public virtual int Editar_Citas(Nullable<int> idCita, Nullable<int> idUsuario, Nullable<int> idDoctor, string condicion, Nullable<System.DateTime> hora, Nullable<System.DateTime> dia, Nullable<bool> status)
        {
            var idCitaParameter = idCita.HasValue ?
                new ObjectParameter("IdCita", idCita) :
                new ObjectParameter("IdCita", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idDoctorParameter = idDoctor.HasValue ?
                new ObjectParameter("IdDoctor", idDoctor) :
                new ObjectParameter("IdDoctor", typeof(int));
    
            var condicionParameter = condicion != null ?
                new ObjectParameter("Condicion", condicion) :
                new ObjectParameter("Condicion", typeof(string));
    
            var horaParameter = hora.HasValue ?
                new ObjectParameter("Hora", hora) :
                new ObjectParameter("Hora", typeof(System.DateTime));
    
            var diaParameter = dia.HasValue ?
                new ObjectParameter("Dia", dia) :
                new ObjectParameter("Dia", typeof(System.DateTime));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Editar_Citas", idCitaParameter, idUsuarioParameter, idDoctorParameter, condicionParameter, horaParameter, diaParameter, statusParameter);
        }
    
        public virtual int Editar_Datos_Planilla(Nullable<int> idPlanilla, Nullable<int> idDoctor, Nullable<System.DateTime> fecha, Nullable<int> horasT, Nullable<decimal> salBrut, Nullable<decimal> seguro, Nullable<decimal> deducc, Nullable<decimal> extra, Nullable<decimal> salNet)
        {
            var idPlanillaParameter = idPlanilla.HasValue ?
                new ObjectParameter("IdPlanilla", idPlanilla) :
                new ObjectParameter("IdPlanilla", typeof(int));
    
            var idDoctorParameter = idDoctor.HasValue ?
                new ObjectParameter("IdDoctor", idDoctor) :
                new ObjectParameter("IdDoctor", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var horasTParameter = horasT.HasValue ?
                new ObjectParameter("HorasT", horasT) :
                new ObjectParameter("HorasT", typeof(int));
    
            var salBrutParameter = salBrut.HasValue ?
                new ObjectParameter("SalBrut", salBrut) :
                new ObjectParameter("SalBrut", typeof(decimal));
    
            var seguroParameter = seguro.HasValue ?
                new ObjectParameter("Seguro", seguro) :
                new ObjectParameter("Seguro", typeof(decimal));
    
            var deduccParameter = deducc.HasValue ?
                new ObjectParameter("Deducc", deducc) :
                new ObjectParameter("Deducc", typeof(decimal));
    
            var extraParameter = extra.HasValue ?
                new ObjectParameter("Extra", extra) :
                new ObjectParameter("Extra", typeof(decimal));
    
            var salNetParameter = salNet.HasValue ?
                new ObjectParameter("SalNet", salNet) :
                new ObjectParameter("SalNet", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Editar_Datos_Planilla", idPlanillaParameter, idDoctorParameter, fechaParameter, horasTParameter, salBrutParameter, seguroParameter, deduccParameter, extraParameter, salNetParameter);
        }
    
        public virtual int Editar_Datos_Usuario(string nombre, string apellido1, string apellido2, string cedula, Nullable<int> telefono, string email, string genero, Nullable<System.DateTime> fechaNacimiento, string contrasenna, Nullable<int> tipoUsuario, Nullable<bool> state, Nullable<int> iDusuario)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var telefonoParameter = telefono.HasValue ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            var tipoUsuarioParameter = tipoUsuario.HasValue ?
                new ObjectParameter("TipoUsuario", tipoUsuario) :
                new ObjectParameter("TipoUsuario", typeof(int));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(bool));
    
            var iDusuarioParameter = iDusuario.HasValue ?
                new ObjectParameter("IDusuario", iDusuario) :
                new ObjectParameter("IDusuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Editar_Datos_Usuario", nombreParameter, apellido1Parameter, apellido2Parameter, cedulaParameter, telefonoParameter, emailParameter, generoParameter, fechaNacimientoParameter, contrasennaParameter, tipoUsuarioParameter, stateParameter, iDusuarioParameter);
        }
    
        public virtual int Editar_Expediente(Nullable<int> idExpediente, Nullable<int> idUsuario, Nullable<int> idDoctor, string padecimiento, string tratamiento)
        {
            var idExpedienteParameter = idExpediente.HasValue ?
                new ObjectParameter("IdExpediente", idExpediente) :
                new ObjectParameter("IdExpediente", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idDoctorParameter = idDoctor.HasValue ?
                new ObjectParameter("IdDoctor", idDoctor) :
                new ObjectParameter("IdDoctor", typeof(int));
    
            var padecimientoParameter = padecimiento != null ?
                new ObjectParameter("Padecimiento", padecimiento) :
                new ObjectParameter("Padecimiento", typeof(string));
    
            var tratamientoParameter = tratamiento != null ?
                new ObjectParameter("Tratamiento", tratamiento) :
                new ObjectParameter("Tratamiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Editar_Expediente", idExpedienteParameter, idUsuarioParameter, idDoctorParameter, padecimientoParameter, tratamientoParameter);
        }
    
        public virtual int Registrar_BitacoraA(string email, Nullable<System.DateTime> fechaHora, string descripcion, string origen)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var fechaHoraParameter = fechaHora.HasValue ?
                new ObjectParameter("FechaHora", fechaHora) :
                new ObjectParameter("FechaHora", typeof(System.DateTime));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Registrar_BitacoraA", emailParameter, fechaHoraParameter, descripcionParameter, origenParameter);
        }
    
        public virtual int Registrar_BitacoraE(string email, Nullable<System.DateTime> fechaHora, Nullable<int> codigoError, string descripcion, string origen)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var fechaHoraParameter = fechaHora.HasValue ?
                new ObjectParameter("FechaHora", fechaHora) :
                new ObjectParameter("FechaHora", typeof(System.DateTime));
    
            var codigoErrorParameter = codigoError.HasValue ?
                new ObjectParameter("CodigoError", codigoError) :
                new ObjectParameter("CodigoError", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Registrar_BitacoraE", emailParameter, fechaHoraParameter, codigoErrorParameter, descripcionParameter, origenParameter);
        }
    
        public virtual int Registrar_Cita(Nullable<int> idUsuario, Nullable<int> idDoctor, string condicion, Nullable<System.DateTime> hora, Nullable<System.DateTime> dia)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idDoctorParameter = idDoctor.HasValue ?
                new ObjectParameter("IdDoctor", idDoctor) :
                new ObjectParameter("IdDoctor", typeof(int));
    
            var condicionParameter = condicion != null ?
                new ObjectParameter("Condicion", condicion) :
                new ObjectParameter("Condicion", typeof(string));
    
            var horaParameter = hora.HasValue ?
                new ObjectParameter("Hora", hora) :
                new ObjectParameter("Hora", typeof(System.DateTime));
    
            var diaParameter = dia.HasValue ?
                new ObjectParameter("Dia", dia) :
                new ObjectParameter("Dia", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Registrar_Cita", idUsuarioParameter, idDoctorParameter, condicionParameter, horaParameter, diaParameter);
        }
    
        public virtual int Registrar_Datos_Usuario(string nombre, string apellido1, string apellido2, string cedula, Nullable<int> telefono, string email, string genero, Nullable<System.DateTime> fechaNacimiento, string contrasenna, Nullable<int> tipoUsuario)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var telefonoParameter = telefono.HasValue ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            var tipoUsuarioParameter = tipoUsuario.HasValue ?
                new ObjectParameter("TipoUsuario", tipoUsuario) :
                new ObjectParameter("TipoUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Registrar_Datos_Usuario", nombreParameter, apellido1Parameter, apellido2Parameter, cedulaParameter, telefonoParameter, emailParameter, generoParameter, fechaNacimientoParameter, contrasennaParameter, tipoUsuarioParameter);
        }
    
        public virtual int Registrar_Doctor(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Registrar_Doctor", idUsuarioParameter);
        }
    
        public virtual int Registrar_Expediente(Nullable<int> idUsuario, Nullable<int> idDoctor, string padecimiento, string tratamiento)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idDoctorParameter = idDoctor.HasValue ?
                new ObjectParameter("IdDoctor", idDoctor) :
                new ObjectParameter("IdDoctor", typeof(int));
    
            var padecimientoParameter = padecimiento != null ?
                new ObjectParameter("Padecimiento", padecimiento) :
                new ObjectParameter("Padecimiento", typeof(string));
    
            var tratamientoParameter = tratamiento != null ?
                new ObjectParameter("Tratamiento", tratamiento) :
                new ObjectParameter("Tratamiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Registrar_Expediente", idUsuarioParameter, idDoctorParameter, padecimientoParameter, tratamientoParameter);
        }
    
        public virtual int Registrar_Planilla(Nullable<int> idDoctor, Nullable<System.DateTime> fecha, Nullable<int> horasT, Nullable<decimal> salBrut, Nullable<decimal> seguro, Nullable<decimal> deducc, Nullable<decimal> extra, Nullable<decimal> salNet)
        {
            var idDoctorParameter = idDoctor.HasValue ?
                new ObjectParameter("IdDoctor", idDoctor) :
                new ObjectParameter("IdDoctor", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var horasTParameter = horasT.HasValue ?
                new ObjectParameter("HorasT", horasT) :
                new ObjectParameter("HorasT", typeof(int));
    
            var salBrutParameter = salBrut.HasValue ?
                new ObjectParameter("SalBrut", salBrut) :
                new ObjectParameter("SalBrut", typeof(decimal));
    
            var seguroParameter = seguro.HasValue ?
                new ObjectParameter("Seguro", seguro) :
                new ObjectParameter("Seguro", typeof(decimal));
    
            var deduccParameter = deducc.HasValue ?
                new ObjectParameter("Deducc", deducc) :
                new ObjectParameter("Deducc", typeof(decimal));
    
            var extraParameter = extra.HasValue ?
                new ObjectParameter("Extra", extra) :
                new ObjectParameter("Extra", typeof(decimal));
    
            var salNetParameter = salNet.HasValue ?
                new ObjectParameter("SalNet", salNet) :
                new ObjectParameter("SalNet", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Registrar_Planilla", idDoctorParameter, fechaParameter, horasTParameter, salBrutParameter, seguroParameter, deduccParameter, extraParameter, salNetParameter);
        }
    }
}
