//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisioAPI.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBITACORA
    {
        public int ConsecutivoError { get; set; }
        public int IDusuario { get; set; }
        public System.DateTime FechaHora { get; set; }
        public int CodigoError { get; set; }
        public string Descripcion { get; set; }
        public string Origen { get; set; }
    }
}
