//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisioAPI.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Citas = new HashSet<Citas>();
            this.Comentarios = new HashSet<Comentarios>();
            this.Doctores = new HashSet<Doctores>();
            this.Expediente = new HashSet<Expediente>();
        }
    
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string cedula { get; set; }
        public int telefono { get; set; }
        public string email { get; set; }
        public string genero { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Contrasenna { get; set; }
        public int idTipoUsuarioFk { get; set; }
        public bool state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas> Citas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentarios> Comentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctores> Doctores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expediente> Expediente { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
